-- 코드를 작성해주세요
-- 2세대 찾기
SELECT C.ID AS ID
FROM (SELECT B.ID AS ID
FROM ECOLI_DATA A JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
WHERE A.PARENT_ID IS NULL) AS ECOLI JOIN ECOLI_DATA C ON ECOLI.ID = C.PARENT_ID
ORDER BY C.ID ASC;