SELECT ED.ID AS ID, CASE WHEN ED.p_rank <=0.25 THEN 'CRITICAL' WHEN ED.p_rank <=0.50 THEN 'HIGH' WHEN ED.p_rank<=0.75 then 'MEDIUM' ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS p_rank FROM ECOLI_DATA) AS ED
ORDER BY ID ASC;