-- 코드를 입력하세요
SELECT YEAR(C.SALES_DATE) AS YEAR, MONTH(C.SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)='2021'),1) AS PURCHASED_RATIO
FROM (SELECT ONLINE_SALE_ID, B.USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = '2021') C
GROUP BY YEAR(C.SALES_DATE), MONTH(C.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;

-- 21년에 가입한 전체 회원 수
# SELECT COUNT(USER_ID)
# FROM USER_INFO
# WHERE YEAR(JOINED) = '2021' 