WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID, A.PARENT_ID, GEN+1 AS GEN
    FROM ECOLI_DATA A JOIN TREE B ON A.PARENT_ID = B.ID
)
-- SELECT *
SELECT COUNT(ID) AS COUNT, A.GEN AS GENERATION 
FROM TREE A
WHERE NOT EXISTS(SELECT 1
      FROM TREE B
    WHERE B.PARENT_ID = A.ID)
GROUP BY A.GEN
ORDER BY GENERATION ASC;

