-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME,"%H") AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
-- WHERE DATE_FORMAT(DATETIME,"%h") >= '09' AND DATE_FORMAT(DATETIME,"%h")< '20'
GROUP BY DATE_FORMAT(DATETIME,"%H")
HAVING HOUR >= '09' AND HOUR < '20'
ORDER BY HOUR ASC;