-- 코드를 작성해주세요
SELECT T.SCORE, T.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM(SELECT SUM(SCORE) AS SCORE, EMP_NO
FROM HR_GRADE
WHERE YEAR = '2022'
GROUP BY EMP_NO) AS T JOIN HR_EMPLOYEES H ON T.EMP_NO = H.EMP_NO 
ORDER BY SCORE DESC
LIMIT 1;


